### PR TITLE
chore: add prettier and configure

### PR DESCRIPTION
**Pull request by aceres**
add prettier plugin
configure prettier
add git hooks
add pre-commit for running prettier before to commit any files

Doc: https://prettier.io/docs/en/install.html

### CODE REVIEW

**Review by Nigothazine — COMMENTED** [review]
all good - please rebase so I can squash and merge it 🙌🏼

**Comment by aceres** [comment]
> all good - please rebase so I can squash and merge it 🙌🏼

Cool - I will do it with pleasure. Thanks for reviewing.

**Comment by aceres** [comment]
Hello @Nigothazine, I just could resolved conflicts and rebased the branch as well. Feel free to check it. Thanks a lot.

**Comment by aceres** [comment]
Hi @Nigothazine , there is an interesting plugin ESLint for us which we probably need it as well. We can discuss about it and add this plugin later.
Link: https://github.com/prettier/eslint-config-prettier
(ESLiint Config)

**Pull request merged**
